-- 设备管理 H2 DDL
CREATE TABLE IF NOT EXISTS sys_device (
    id BIGINT PRIMARY KEY,
    device_name VARCHAR(100) NOT NULL,
    device_code VARCHAR(50) NOT NULL UNIQUE,
    device_type INT NOT NULL,
    device_model VARCHAR(100),
    gb_device_id VARCHAR(50),
    rtsp_main_url VARCHAR(500),
    rtsp_sub_url VARCHAR(500),
    longitude DECIMAL(12,8),
    latitude DECIMAL(12,8),
    location_text VARCHAR(200),
    region_id BIGINT,
    pic_url VARCHAR(500),
    device_ip VARCHAR(50),
    online_status INT DEFAULT 0,
    sim_card_no VARCHAR(20),
    monthly_flow_limit INT,
    monthly_flow_used INT DEFAULT 0,
    next_maintenance_date DATE,
    maintenance_cycle INT,
    install_date DATE,
    remark VARCHAR(500),
    status INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted INT DEFAULT 0
);
